### ISSUE TITLE
WARNING: The convert command is deprecated in IMv7, use "magick"

### ISSUE THREAD

**Issue by asm0dey** [hackerb9/lsix#77]
When I run the command on my arch I get many messages like the one in the subj

**Comment by hackerb9** [comment]
Thank you for the bug report. I believe this is fixed in the latest release, but please let me know if there are still problems.

**Comment by properCase** [comment]
It is still a problem.  I upgraded to the latest version with `brew upgrade lsix` and also installed a fresh copy on a different computer and version 1.9 is still throwing the same error

**Comment by hackerb9** [comment]
How odd. What does `type -p magick` return for you?

P.S. Are you sure Brew installed version 1.9? I didn't know it worked directly from the github release. When you say you installed a fresh copy, do you mean you [downloaded the script](https://raw.githubusercontent.com/hackerb9/lsix/master/lsix) by hand?

**Comment by properCase** [comment]
I just ran a `brew upgrade lsix` and it said the latest version of lsix was 1.9

**Comment by hackerb9** [comment]
Please try now. Turns out IM7 had deprecated using `magick convert` as well.

**Comment by jiawen** [comment]
> Please try now. Turns out IM7 had deprecated using `magick convert` as well.

Working now! lsix on Homebrew is now at 1.9.1.

**Comment by properCase** [comment]
> It works!  Thank you @hackerb9 !
